CREATE TABLE PERSON  (
     ID INTEGER NOT NULL,
     NAME VARCHAR(100) NOT NULL,
     LAST_NAME VARCHAR(100) NOT NULL,
     AGE INT NOT NULL,
     CREATION_DATE DATE NOT NULL,
     ADDRESS VARCHAR(100),
     STATUS VARCHAR(100) NOT NULL,
     GENDER VARCHAR(100),
     COUNTRY VARCHAR(100),
     JOB_EXECUTION_ID INTEGER,
     PRIMARY KEY(ID)
) ;

SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE;